// <auto-generated />
using System;
using Buzzify.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Buzzify.Infrastructure.Migrations
{
    [DbContext(typeof(BuzzifyDbContext))]
    [Migration("20260327054914_AddAdminControlFields")]
    partial class AddAdminControlFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlbumDaLuu", b =>
                {
                    b.Property<string>("IdNguoiDung")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("id_nguoi_dung");

                    b.Property<string>("IdAlbum")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("id_album");

                    b.HasKey("IdNguoiDung", "IdAlbum")
                        .HasName("PK__album_da__0297EDE35857E273");

                    b.HasIndex("IdAlbum");

                    b.ToTable("album_da_luu", (string)null);
                });

            modelBuilder.Entity("Buzzify.Core.Entities.Album", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("AnhBia")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("anh_bia");

                    b.Property<string>("ArtistId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("artist_id");

                    b.Property<DateOnly?>("NgayPhatHanh")
                        .HasColumnType("date")
                        .HasColumnName("ngay_phat_hanh");

                    b.Property<DateTime?>("ScheduledPublishDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("scheduled_publish_date");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tieu_de");

                    b.HasKey("Id")
                        .HasName("PK__album__3213E83F491DAF30");

                    b.HasIndex("ArtistId");

                    b.HasIndex(new[] { "TieuDe" }, "idx_album_tieu_de");

                    b.ToTable("album", (string)null);
                });

            modelBuilder.Entity("Buzzify.Core.Entities.Artist", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("anh_dai_dien");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FollowerCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("follower_count");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("profile_id");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten");

                    b.HasKey("Id")
                        .HasName("PK__artists__3213E83F1E17383B");

                    b.HasIndex("ProfileId");

                    b.HasIndex(new[] { "Ten" }, "idx_artists_ten");

                    b.ToTable("artists", (string)null);
                });

            modelBuilder.Entity("Buzzify.Core.Entities.BaiHatTrongDailyMix", b =>
                {
                    b.Property<string>("MixId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("mix_id");

                    b.Property<string>("SongId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("song_id");

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int")
                        .HasColumnName("thu_tu");

                    b.HasKey("MixId", "SongId")
                        .HasName("PK__bai_hat___1CC42EDE9BB371CF");

                    b.HasIndex("SongId");

                    b.ToTable("bai_hat_trong_daily_mix", (string)null);
                });

            modelBuilder.Entity("Buzzify.Core.Entities.BaiHatTrongPlaylist", b =>
                {
                    b.Property<string>("PlaylistId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("playlist_id");

                    b.Property<string>("SongId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("song_id");

                    b.Property<DateTime?>("NgayThem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_them")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("PlaylistId", "SongId")
                        .HasName("PK__bai_hat___21CF4EF115816D46");

                    b.HasIndex("SongId");

                    b.ToTable("bai_hat_trong_playlist", (string)null);
                });

            modelBuilder.Entity("Buzzify.Core.Entities.LichSuNghe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("IdNguoiDung")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("id_nguoi_dung");

                    b.Property<DateTime?>("NgayNghe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_nghe")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SongId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("song_id");

                    b.HasKey("Id")
                        .HasName("PK__lich_su___3213E83FF3A4F20D");

                    b.HasIndex("SongId");

                    b.HasIndex(new[] { "IdNguoiDung", "NgayNghe" }, "idx_lich_su_nghe_user_time")
                        .IsDescending(false, true);

                    b.ToTable("lich_su_nghe", (string)null);
                });

            modelBuilder.Entity("Buzzify.Core.Entities.Playlist", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("AnhBia")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("anh_bia");

                    b.Property<bool?>("CongKhai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("cong_khai");

                    b.Property<string>("IdNguoiTao")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("id_nguoi_tao");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiPlaylist")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("user_created")
                        .HasColumnName("loai_playlist");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten");

                    b.HasKey("Id")
                        .HasName("PK__playlist__3213E83F54BD9D14");

                    b.HasIndex("IdNguoiTao");

                    b.ToTable("playlists", (string)null);
                });

            modelBuilder.Entity("Buzzify.Core.Entities.Profile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("anh_dai_dien");

                    b.Property<string>("AnhDaiDienProvider")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("anh_dai_dien_provider");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bio");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ho_ten");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit")
                        .HasColumnName("is_email_verified");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<double?>("LastPosition")
                        .HasColumnType("float")
                        .HasColumnName("last_position");

                    b.Property<string>("LastQueueIds")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_queue_ids");

                    b.Property<string>("LastSongId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("last_song_id");

                    b.Property<string>("LastSourceInfo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_source_info");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("link");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("provider_id");

                    b.Property<string>("VaiTro")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("user")
                        .HasColumnName("vai_tro");

                    b.Property<DateTime?>("VerificationCodeExpiry")
                        .HasColumnType("datetime")
                        .HasColumnName("verification_code_expiry");

                    b.Property<string>("VerificationCodeHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("verification_code_hash");

                    b.HasKey("Id")
                        .HasName("PK__profiles__3213E83FF47D26C4");

                    b.HasIndex(new[] { "Provider", "ProviderId" }, "UQ_provider_id")
                        .IsUnique();

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("Buzzify.Core.Entities.Song", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("AnhBia")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("anh_bia");

                    b.Property<string>("ArtistId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("artist_id");

                    b.Property<string>("IdAlbum")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("id_album");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("bit");

                    b.Property<int?>("LuotNghe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("luot_nghe");

                    b.Property<DateTime?>("NgayTaiLen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tai_len")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NgheSiHopTac")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nghe_si_hop_tac");

                    b.Property<DateTime?>("ScheduledPublishDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("scheduled_publish_date");

                    b.Property<int?>("ThoiLuongGiay")
                        .HasColumnType("int")
                        .HasColumnName("thoi_luong_giay");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tieu_de");

                    b.Property<int?>("TrackNumber")
                        .HasColumnType("int")
                        .HasColumnName("track_number");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("published")
                        .HasColumnName("trang_thai");

                    b.Property<string>("UploaderId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("uploader_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("PK__songs__3213E83F4E37F8AB");

                    b.HasIndex("ArtistId");

                    b.HasIndex("IdAlbum");

                    b.HasIndex("UploaderId");

                    b.HasIndex(new[] { "TieuDe" }, "idx_songs_tieu_de");

                    b.ToTable("songs", (string)null);
                });

            modelBuilder.Entity("Buzzify.Core.Entities.TheLoai", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("SearchTags")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("search_tags");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten");

                    b.HasKey("Id")
                        .HasName("PK__the_loai__3213E83FC09AFAB6");

                    b.HasIndex(new[] { "Ten" }, "UQ__the_loai__DC107AB1F0019427")
                        .IsUnique();

                    b.ToTable("the_loai", (string)null);
                });

            modelBuilder.Entity("Buzzify.Core.Entities.UserDailyMix", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("IdNguoiDung")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("id_nguoi_dung");

                    b.Property<string>("IdTheLoaiChinh")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("id_the_loai_chinh");

                    b.Property<DateOnly?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tieu_de");

                    b.HasKey("Id")
                        .HasName("PK__user_dai__3213E83F37346270");

                    b.HasIndex("IdNguoiDung");

                    b.HasIndex("IdTheLoaiChinh");

                    b.ToTable("user_daily_mixes", (string)null);
                });

            modelBuilder.Entity("Buzzify.Core.Entities.VwUserFavoriteGenre", b =>
                {
                    b.Property<string>("IdNguoiDung")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("id_nguoi_dung");

                    b.Property<string>("IdTheLoai")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("id_the_loai");

                    b.Property<DateTime?>("LanNgheCuoi")
                        .HasColumnType("datetime")
                        .HasColumnName("lan_nghe_cuoi");

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_the_loai");

                    b.Property<int?>("TongLuotNghe")
                        .HasColumnType("int")
                        .HasColumnName("tong_luot_nghe");

                    b.ToTable((string)null);

                    b.ToView("vw_user_favorite_genres", (string)null);
                });

            modelBuilder.Entity("NgheSiTheoDoi", b =>
                {
                    b.Property<string>("IdNguoiDung")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("id_nguoi_dung");

                    b.Property<string>("ArtistId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("artist_id");

                    b.HasKey("IdNguoiDung", "ArtistId")
                        .HasName("PK__nghe_si___731BA51EF3826680");

                    b.HasIndex("ArtistId");

                    b.ToTable("nghe_si_theo_doi", (string)null);
                });

            modelBuilder.Entity("PlaylistDaLuu", b =>
                {
                    b.Property<string>("IdNguoiDung")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("id_nguoi_dung");

                    b.Property<string>("PlaylistId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("playlist_id");

                    b.HasKey("IdNguoiDung", "PlaylistId")
                        .HasName("PK__playlist__6A6F605FB548F51F");

                    b.HasIndex("PlaylistId");

                    b.ToTable("playlist_da_luu", (string)null);
                });

            modelBuilder.Entity("TheLoaiAlbum", b =>
                {
                    b.Property<string>("IdAlbum")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("id_album");

                    b.Property<string>("IdTheLoai")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("id_the_loai");

                    b.HasKey("IdAlbum", "IdTheLoai")
                        .HasName("PK__the_loai__69A2A47E96A9542F");

                    b.HasIndex("IdTheLoai");

                    b.ToTable("the_loai_album", (string)null);
                });

            modelBuilder.Entity("TheLoaiArtist", b =>
                {
                    b.Property<string>("ArtistId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("artist_id");

                    b.Property<string>("IdTheLoai")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("id_the_loai");

                    b.HasKey("ArtistId", "IdTheLoai")
                        .HasName("PK__the_loai__71662BA966A5BAE2");

                    b.HasIndex("IdTheLoai");

                    b.ToTable("the_loai_artist", (string)null);
                });

            modelBuilder.Entity("TheLoaiPlaylist", b =>
                {
                    b.Property<string>("PlaylistId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("playlist_id");

                    b.Property<string>("IdTheLoai")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("id_the_loai");

                    b.HasKey("PlaylistId", "IdTheLoai")
                        .HasName("PK__the_loai__E62A7FB88C9FB010");

                    b.HasIndex("IdTheLoai");

                    b.ToTable("the_loai_playlist", (string)null);
                });

            modelBuilder.Entity("AlbumDaLuu", b =>
                {
                    b.HasOne("Buzzify.Core.Entities.Album", null)
                        .WithMany()
                        .HasForeignKey("IdAlbum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__album_da___id_al__6C190EBB");

                    b.HasOne("Buzzify.Core.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("IdNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__album_da___id_ng__6D0D32F4");
                });

            modelBuilder.Entity("Buzzify.Core.Entities.Album", b =>
                {
                    b.HasOne("Buzzify.Core.Entities.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__album__artist_id__6B24EA82");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Buzzify.Core.Entities.Artist", b =>
                {
                    b.HasOne("Buzzify.Core.Entities.Profile", "Profile")
                        .WithMany("Artists")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_artists_profiles");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Buzzify.Core.Entities.BaiHatTrongDailyMix", b =>
                {
                    b.HasOne("Buzzify.Core.Entities.UserDailyMix", "Mix")
                        .WithMany("BaiHatTrongDailyMixes")
                        .HasForeignKey("MixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__bai_hat_t__mix_i__208CD6FA");

                    b.HasOne("Buzzify.Core.Entities.Song", "Song")
                        .WithMany("BaiHatTrongDailyMixes")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__bai_hat_t__song___2180FB33");

                    b.Navigation("Mix");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Buzzify.Core.Entities.BaiHatTrongPlaylist", b =>
                {
                    b.HasOne("Buzzify.Core.Entities.Playlist", "Playlist")
                        .WithMany("BaiHatTrongPlaylists")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__bai_hat_t__playl__6E01572D");

                    b.HasOne("Buzzify.Core.Entities.Song", "Song")
                        .WithMany("BaiHatTrongPlaylists")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__bai_hat_t__song___6EF57B66");

                    b.Navigation("Playlist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Buzzify.Core.Entities.LichSuNghe", b =>
                {
                    b.HasOne("Buzzify.Core.Entities.Profile", "IdNguoiDungNavigation")
                        .WithMany("LichSuNghes")
                        .HasForeignKey("IdNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__lich_su_n__id_ng__6FE99F9F");

                    b.HasOne("Buzzify.Core.Entities.Song", "Song")
                        .WithMany("LichSuNghes")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__lich_su_n__song___70DDC3D8");

                    b.Navigation("IdNguoiDungNavigation");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Buzzify.Core.Entities.Playlist", b =>
                {
                    b.HasOne("Buzzify.Core.Entities.Profile", "IdNguoiTaoNavigation")
                        .WithMany("Playlists")
                        .HasForeignKey("IdNguoiTao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__playlists__id_ng__75A278F5");

                    b.Navigation("IdNguoiTaoNavigation");
                });

            modelBuilder.Entity("Buzzify.Core.Entities.Song", b =>
                {
                    b.HasOne("Buzzify.Core.Entities.Artist", "Artist")
                        .WithMany("Songs")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__songs__artist_id__76969D2E");

                    b.HasOne("Buzzify.Core.Entities.Album", "IdAlbumNavigation")
                        .WithMany("Songs")
                        .HasForeignKey("IdAlbum")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__songs__id_album__778AC167");

                    b.HasOne("Buzzify.Core.Entities.Profile", "Uploader")
                        .WithMany("Songs")
                        .HasForeignKey("UploaderId")
                        .HasConstraintName("FK_songs_uploader");

                    b.Navigation("Artist");

                    b.Navigation("IdAlbumNavigation");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("Buzzify.Core.Entities.UserDailyMix", b =>
                {
                    b.HasOne("Buzzify.Core.Entities.Profile", "IdNguoiDungNavigation")
                        .WithMany("UserDailyMixes")
                        .HasForeignKey("IdNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__user_dail__id_ng__1CBC4616");

                    b.HasOne("Buzzify.Core.Entities.TheLoai", "IdTheLoaiChinhNavigation")
                        .WithMany("UserDailyMixes")
                        .HasForeignKey("IdTheLoaiChinh")
                        .HasConstraintName("FK__user_dail__id_th__1DB06A4F");

                    b.Navigation("IdNguoiDungNavigation");

                    b.Navigation("IdTheLoaiChinhNavigation");
                });

            modelBuilder.Entity("NgheSiTheoDoi", b =>
                {
                    b.HasOne("Buzzify.Core.Entities.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__nghe_si_t__artis__71D1E811");

                    b.HasOne("Buzzify.Core.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("IdNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__nghe_si_t__id_ng__72C60C4A");
                });

            modelBuilder.Entity("PlaylistDaLuu", b =>
                {
                    b.HasOne("Buzzify.Core.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("IdNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__playlist___id_ng__73BA3083");

                    b.HasOne("Buzzify.Core.Entities.Playlist", null)
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .IsRequired()
                        .HasConstraintName("FK__playlist___playl__74AE54BC");
                });

            modelBuilder.Entity("TheLoaiAlbum", b =>
                {
                    b.HasOne("Buzzify.Core.Entities.Album", null)
                        .WithMany()
                        .HasForeignKey("IdAlbum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__the_loai___id_al__787EE5A0");

                    b.HasOne("Buzzify.Core.Entities.TheLoai", null)
                        .WithMany()
                        .HasForeignKey("IdTheLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__the_loai___id_th__797309D9");
                });

            modelBuilder.Entity("TheLoaiArtist", b =>
                {
                    b.HasOne("Buzzify.Core.Entities.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__the_loai___artis__7A672E12");

                    b.HasOne("Buzzify.Core.Entities.TheLoai", null)
                        .WithMany()
                        .HasForeignKey("IdTheLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__the_loai___id_th__7B5B524B");
                });

            modelBuilder.Entity("TheLoaiPlaylist", b =>
                {
                    b.HasOne("Buzzify.Core.Entities.TheLoai", null)
                        .WithMany()
                        .HasForeignKey("IdTheLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__the_loai___id_th__7C4F7684");

                    b.HasOne("Buzzify.Core.Entities.Playlist", null)
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__the_loai___playl__7D439ABD");
                });

            modelBuilder.Entity("Buzzify.Core.Entities.Album", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("Buzzify.Core.Entities.Artist", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Songs");
                });

            modelBuilder.Entity("Buzzify.Core.Entities.Playlist", b =>
                {
                    b.Navigation("BaiHatTrongPlaylists");
                });

            modelBuilder.Entity("Buzzify.Core.Entities.Profile", b =>
                {
                    b.Navigation("Artists");

                    b.Navigation("LichSuNghes");

                    b.Navigation("Playlists");

                    b.Navigation("Songs");

                    b.Navigation("UserDailyMixes");
                });

            modelBuilder.Entity("Buzzify.Core.Entities.Song", b =>
                {
                    b.Navigation("BaiHatTrongDailyMixes");

                    b.Navigation("BaiHatTrongPlaylists");

                    b.Navigation("LichSuNghes");
                });

            modelBuilder.Entity("Buzzify.Core.Entities.TheLoai", b =>
                {
                    b.Navigation("UserDailyMixes");
                });

            modelBuilder.Entity("Buzzify.Core.Entities.UserDailyMix", b =>
                {
                    b.Navigation("BaiHatTrongDailyMixes");
                });
#pragma warning restore 612, 618
        }
    }
}
